<?php

namespace Database\Seeders;

use App\Models\MonthlyEdition;
use App\Models\MonthlyEditionSection;
use Illuminate\Database\Seeder;

class July2026ShadowsMonthlySectionsSeeder extends Seeder
{
    public function run(): void
    {
        $edition = MonthlyEdition::query()
            ->where(function ($query) {
                $query->where(function ($inner) {
                    $inner->where('month', 7)->where('year', 2026);
                })->orWhere('is_homepage', true);
            })
            ->orderByRaw('CASE WHEN month = 7 AND year = 2026 THEN 0 ELSE 1 END')
            ->orderByDesc('is_homepage')
            ->first();

        if (!$edition) {
            $this->command?->warn('No July 2026 / homepage monthly edition found. Create an edition first, then re-run this seeder.');
            return;
        }

        $sections = $this->sections();

        foreach ($sections as $index => $section) {
            MonthlyEditionSection::updateOrCreate(
                [
                    'monthly_edition_id' => $edition->id,
                    'title' => $section['title'],
                ],
                [
                    'icon' => $section['icon'],
                    'content' => $section['content'],
                    'image' => null,
                    'image_caption' => null,
                    'placement' => $section['placement'],
                    'sort_order' => $index + 1,
                ]
            );
        }

        $this->command?->info('Seeded ' . count($sections) . ' magazine sections onto edition: ' . $edition->title . ' (ID ' . $edition->id . ').');
    }

    private function sections(): array
    {
        return [
            [
                'title' => 'Pull Up a Chair...',
                'icon' => '☕',
                'placement' => MonthlyEditionSection::PLACEMENT_BEFORE,
                'content' => $this->html([
                    '...and spend a moment with the Shadows Family.',
                    "I'm so glad you're here.",
                    "Whether you're reading this at home with a warm cuppa, sitting beside a campfire, travelling in your caravan, or simply enjoying a quiet moment before the day begins, I'd like to welcome you to the very first edition of Shadows Monthly.",
                    'It means so much to have you here.',
                    "It's a cool, fresh winter morning here in Glenreagh today.",
                    "I've just put the kettle on and thought I'd come outside for a few quiet minutes before the day begins.",
                    'This has always been my favourite part of the day.',
                    'Before the phones start ringing.',
                    'Before the printers begin humming away.',
                    'Before life gets busy.',
                    "It's my chance to simply sit, breathe and let my mind wander.",
                    "This morning the black cockatoos were back in the gum trees before I'd even finished my coffee.",
                    "I could hear them chatting away before I saw them. They always seem to arrive together, and, over the years, I've noticed it usually isn't long before we get a little rain.",
                    'The fog was still sitting across the mountains and, as the sun slowly climbed higher, it began shining through the mist.',
                    'I sat there for quite a while, simply taking it all in.',
                    "I found myself wishing I'd brought my camera down with me.",
                    'Then I smiled to myself.',
                    "By the time I'd gone back inside to get it, the cockatoos would probably have flown away.",
                    'It made me wonder...',
                    'Would I have photographed the fog rolling across the mountains?',
                    'The black cockatoos high in the gum trees?',
                    'Or those first rays of sunshine breaking through the mist?',
                    'Sometimes I think the most beautiful photographs are the ones we never get to take.',
                    'Yet somehow...',
                    "They're the ones that stay with us forever.",
                    'As I sat there, my mind wandered, just as it always seems to do.',
                    'I started wondering what people around Australia might be doing this morning.',
                    'Perhaps someone was watching the sunrise over the ocean.',
                    'Maybe another family was packing up the caravan before heading off on their next adventure.',
                    'Someone else might have been enjoying a quiet walk, rugged up against the winter chill.',
                    'Or maybe they were just like me...',
                    'Sitting quietly with a warm cuppa before the day began.',
                    "I think that's one of the lovely things about winter.",
                    'It somehow encourages us to slow down.',
                    'To spend a little more time together.',
                    'To appreciate the little moments that are often missed when life gets busy.',
                    'Then my thoughts wandered to the people who trust us with their memories.',
                    'I was thinking the other day about the people I print for and how, over the years, so many of them have come to feel like family.',
                    "When the phone rings, I can often tell who's calling before they even tell me their name.",
                    'I recognise their voice.',
                    "Before long, we're chatting as though we only spoke yesterday.",
                    'I absolutely love that.',
                    "It's something I never take for granted.",
                    'I feel incredibly honoured that so many people in the photography and scrapbooking communities have trusted our little family with their memories over the years.',
                    'Every photograph.',
                    'Every scrapbook page.',
                    'Every canvas.',
                    "Tells part of someone's story.",
                    "I never forget what a privilege it is that you've trusted us to help preserve those moments.",
                    'Somewhere along the way, many of you became much more than customers.',
                    "We've shared stories about weddings.",
                    'New babies.',
                    'Grandchildren.',
                    'Family holidays.',
                    'Special celebrations.',
                    'And sometimes...',
                    'Even the harder moments in life.',
                    "We've celebrated together.",
                    "We've laughed together.",
                    "And sometimes we've simply listened.",
                    "I think that's why so many of you feel like family.",
                    "Because we haven't just shared photographs.",
                    "We've shared little pieces of life together.",
                    'I think we all need a place where someone knows our name.',
                    'A place where someone remembers our story.',
                    "A place where we're always welcomed with a friendly smile.",
                    "I truly hope that's what Shadows has become for you.",
                    "Because I know that's what you've become for me.",
                    'These quiet mornings remind me to slow down.',
                    'To appreciate the beauty around me.',
                    'To notice the things that are so easy to miss.',
                    'Sometimes they\'re the memories that stay with us forever.',
                    "I hope, wherever you're reading this today, you've found a few quiet moments for yourself as well.",
                    "Now that we've had our little catch-up over a cuppa, I'd love to share a story that's very close to my heart.",
                    'The story behind the name...',
                    'Shadows.',
                ]),
            ],
            [
                'title' => 'Why Her Name Lives On',
                'icon' => '',
                'placement' => MonthlyEditionSection::PLACEMENT_BEFORE,
                'content' => $this->html([
                    'When John and I opened our business, there was never any discussion about what we were going to call it.',
                    'It was always going to be Shadows.',
                    'It just felt right.',
                    'Late last year, we said goodbye to our beautiful Shadow.',
                    'Like so many families who lose a much-loved member of the family, our hearts were broken.',
                    'As we slowly started looking towards the future, we all kept coming back to one simple thought.',
                    "We didn't want Shadow's name to simply become part of our past.",
                    'She had been such an important part of our family, our business and our journey that it only felt right for her name to continue walking beside us.',
                    "That's why, over the coming months, you'll gradually begin seeing the name Shadows Affordable Memories.",
                    "It isn't replacing Shadows Photo Printing & Gift Shop.",
                    'Our printing business will always remain at the heart of everything we do.',
                    'Our website will always be www.shadowsphotoprinting.com.au, and that\'s where you\'ll always be able to find us.',
                    "The new name simply allows us to honour Shadow while we continue building the dreams we've been quietly working on behind the scenes.",
                    'One of those dreams is creating a welcoming Community Art, History & Gift Shop.',
                    'A place where local artists can proudly display and sell their work.',
                    'A place where local history can be celebrated and shared with future generations.',
                    'A place where people can browse handmade gifts, discover something unique, stop in for a cup of tea or coffee, have a chat and simply enjoy spending a little time with us.',
                    "We still have a lot of work ahead of us, but we're excited about what the future holds, and we can't wait to share every step of the journey with you through Shadows Monthly.",
                ]),
            ],
            [
                'title' => 'A New Chapter Begins',
                'icon' => '',
                'placement' => MonthlyEditionSection::PLACEMENT_BEFORE,
                'content' => $this->html([
                    'While Shadow will always be part of our story, every story eventually turns a new page.',
                    'Many of you have already met Joblin, our beautiful Australian Bulldog.',
                    "She's full of personality, loves being around people and, just like Shadow, always seems to know how to make us smile.",
                    "Over the coming months, Joblin will begin her own journey towards becoming my assistance dog, following in Shadow's very special paw prints.",
                    'No dog could ever replace Shadow.',
                    'And we would never ask her to.',
                    "Shadow's story will always be her own.",
                    "Now it's time for Joblin to begin writing hers.",
                    "We can't wait to introduce you to her properly and share her adventures, her funny moments and her journey with you through future editions of Shadows Monthly.",
                    'As I look back on everything Shadow gave our family, I\'m reminded of one very simple thing.',
                    "Life isn't really measured by the number of years we have.",
                    "It's measured by the memories we make, the people we share them with and the moments that stay in our hearts long after they've passed.",
                    'Shadow taught our family that.',
                    'She reminded us to slow down.',
                    'To notice the little things.',
                    'To laugh often.',
                    'To enjoy the journey.',
                    'And, most importantly...',
                    'To make memories together.',
                    "Perhaps that's why preserving memories has become so much more than simply printing photographs for us.",
                    "Every photograph we print tells part of someone's story.",
                    'Every scrapbook page celebrates a family adventure.',
                    'Every canvas hanging on a wall becomes a daily reminder of a special moment.',
                    'Every old photograph we restore helps keep a family\'s history alive for another generation.',
                    'Those memories belong to you.',
                    "We're simply honoured that you trust us to help preserve them.",
                    "As I sit here finishing my coffee this morning, I can't help but wonder...",
                    'What memories are you making?',
                    "Perhaps you've just come home from a caravan trip around Australia.",
                    "Maybe you're planning your next family holiday.",
                    "Perhaps you've welcomed a new baby, celebrated a wedding, watched your grandchildren grow, or simply enjoyed a quiet afternoon in the garden.",
                    "Maybe you've finally found time to sit down and catch up on those scrapbook pages you've been meaning to finish.",
                    "Or perhaps you've taken a photograph that makes you smile every time you look at it.",
                    'Whatever your story is...',
                    "I hope you're taking the time to enjoy it.",
                    "Because one day, today's ordinary moments often become tomorrow's most treasured memories.",
                    "And that's exactly what I'd love to celebrate with you.",
                    "So, grab another cuppa, and let's take a journey around Australia together to celebrate some of the wonderful memories Australians are making every single day.",
                ]),
            ],
            [
                'title' => 'Making Memories Around Australia',
                'icon' => '🇦🇺',
                'placement' => MonthlyEditionSection::PLACEMENT_BEFORE,
                'content' => $this->html([
                    'Celebrating the memories Australians are making.',
                    'You know...',
                    "I've been thinking a lot about winter lately.",
                    "Not because it's cold.",
                    'But because I think winter has a way of helping us notice things we often miss during the rest of the year.',
                    'The mornings seem quieter.',
                    'The light feels softer.',
                    'The stars somehow shine a little brighter.',
                    'Even the smell of a campfire drifting through the air can bring back memories from years ago.',
                    'I often find myself wondering what people all around Australia are doing at this very moment.',
                    'Perhaps somewhere a family has just unhitched their caravan beside a quiet river and is putting the kettle on while the children explore.',
                    'Maybe someone is standing on a headland, patiently waiting for a whale to appear.',
                    "Someone else might be wandering through a little country town they've never visited before, discovering an old church, a tiny museum or a bakery that's been serving locals for generations.",
                    "Further south, there'll be children seeing snow for the very first time.",
                    'Can you imagine the excitement on their faces?',
                    "I don't know about you, but I think I'd spend more time watching their expressions than the snow itself.",
                    'Then, as night falls, families all over Australia will be looking up at some of the clearest skies of the year.',
                    "There's something magical about a winter sky.",
                    "It's one of those things we don't always stop to appreciate until we take the time to simply stand still.",
                    "Sometimes I think Australia isn't just beautiful because of the places we visit.",
                    "I think it's beautiful because of the moments we experience while we're there.",
                    'The laughter around a campfire.',
                    'The smell of fresh bread from a country bakery.',
                    'The silence of a misty morning.',
                    'The excitement of discovering somewhere new.',
                    'The joy of simply being together.',
                    'Those are the moments that stay with us.',
                    "Those are the moments that quietly become part of our family's story.",
                    'And that made me wonder...',
                    'What memories are you making this winter?',
                    "Perhaps you've discovered a beautiful place close to home.",
                    "Maybe you're planning a road trip.",
                    "Or perhaps your favourite memories this month won't be made hundreds of kilometres away at all.",
                    "Maybe they'll be made in your own backyard, with the people you love most.",
                    "Sometimes the best journeys aren't measured by distance.",
                    "They're measured by the memories we bring home.",
                    'As I was thinking about where Australians might be making memories this month, my thoughts wandered back home to Glenreagh.',
                    'July is always a lovely time here.',
                    'On the first Saturday of the month, our little village comes together for the Glenreagh Markets. It\'s one of those mornings where people slow down, enjoy a chat over a coffee, wander through the stalls and catch up with familiar faces.',
                    'Then, a few weeks later, the whole town comes alive again for the Glenreagh Timber Festival.',
                    "It's always wonderful to see visitors arriving from near and far, all coming together to celebrate our timber heritage and enjoy a great day in our little community.",
                    "This year, you'll find the whole Shadows Family there too. John will have our beautiful Mack Super-Liner, Joblin will no doubt be making new friends, and together we'll be helping families keep a special memory of their day in Glenreagh.",
                    "If our paths happen to cross, I'd love you to stop and say hello. It would be lovely to meet you, have a chat and hear about the memories you're making.",
                ]),
            ],
            [
                'title' => 'Why We Print',
                'icon' => '❤️',
                'placement' => MonthlyEditionSection::PLACEMENT_BEFORE,
                'content' => $this->html([
                    'One of the questions I\'m often asked is,',
                    '"Do people still print their photographs?"',
                    'My answer is always the same...',
                    'More than ever.',
                    "In fact, over the past few years, we've noticed something quite special happening.",
                    'People are coming back to printing.',
                    'Not because technology has changed.',
                    'But because the way we value our memories has changed.',
                    'More and more families are slowing down, pulling out the photo albums and spending time together looking back at the moments that made them smile.',
                    "They're also realising something we've all experienced at one time or another...",
                    'Phones get replaced.',
                    'Hard drives fail.',
                    'Computers crash.',
                    'Accounts get forgotten.',
                    'And sometimes, precious photographs are lost forever.',
                    'A printed photograph is different.',
                    'You can hold it.',
                    'Frame it.',
                    'Place it in a photo album.',
                    'Pass it around the table.',
                    'Or simply leave it on the kitchen bench where it makes you smile every time you walk past.',
                    'One of my favourite moments is watching people collect their prints.',
                    'Almost every day someone says,',
                    '"I forgot how beautiful it is to hold a real photograph."',
                    'Or...',
                    '"I can\'t wait to show these to Mum."',
                    'Or...',
                    '"We\'re going to sit down tonight and go through these together."',
                    'Those are the moments I love.',
                    "Because that's when I realise we're not simply printing photographs.",
                    "We're helping families relive memories.",
                    "And I think that's something very special.",
                    'That got me thinking...',
                    "If this month's stories have inspired you to print a few more memories of your own, we'd love to help.",
                ]),
            ],
            [
                'title' => 'July Inspiration',
                'icon' => '🌿',
                'placement' => MonthlyEditionSection::PLACEMENT_BEFORE,
                'content' => $this->html([
                    "This month we're celebrating the memories that deserve to be enjoyed, not just stored away.",
                    "Whether it's a collection of photographs telling the story of a family holiday, a favourite image displayed proudly on the wall, or the everyday moments that make you smile, every print becomes part of your family's story.",
                    "Long after the moment has passed, it's something you can hold, share and enjoy for years to come.",
                ]) . '<h3>📖 6 × 8 Photo Prints</h3>' . $this->html([
                    'Just $0.85 each',
                    '13th – 19th July',
                    'Perfect for those everyday moments, family holidays and all the little memories waiting to find their place in a photo album.',
                ]) . '<h3>🖼️ Canvas Prints</h3>' . $this->html([
                    '10% off throughout July',
                    'Some photographs deserve more than a place on your phone.',
                    'A beautiful canvas can turn a favourite memory into something you enjoy every single day.',
                    "Whether you're creating a photo album, printing memories from your latest adventure or choosing one special photograph to display in your home, we'd love to help you preserve the moments that matter most.",
                    'From our family to yours... happy memory making.',
                ]),
            ],
            [
                'title' => 'A Little Note That Made Our Day',
                'icon' => '',
                'placement' => MonthlyEditionSection::PLACEMENT_BEFORE,
                'content' => $this->html([
                    'Every now and then we receive a message that reminds us why we love doing what we do.',
                    'This one made us smile.',
                ]) . '<blockquote><p>“Can\'t recommend Shadows Photo Printing highly enough. There\'s a lot to be said for dealing with a family business. Such friendly communication, prompt service and the end product was just amazing! I don\'t do reviews very often, but this company is a STANDOUT!!”</p></blockquote>' . $this->html([
                    'Thank you for taking the time to write such kind words.',
                    "Messages like these mean more to our family than you'll ever know.",
                ]),
            ],
            [
                'title' => "Joblin's Corner",
                'icon' => '🐾',
                'placement' => MonthlyEditionSection::PLACEMENT_BEFORE,
                'content' => $this->html([
                    'Well...',
                    "I think Joblin has already worked out that she's meant to keep an eye on me.",
                    'Yesterday I was chatting to a lovely customer on the phone when she suddenly asked,',
                    '"Terri... is that Joblin snoring, or is it my cat?"',
                    "I couldn't help but laugh.",
                    'I looked over, and there was Joblin lying beside me, sound asleep...',
                    'Well, almost.',
                    'She had one eye open, quietly watching me while somehow managing to snore at the same time!',
                    'I quickly snapped a photo and sent it through to the customer.',
                    'We both had a good laugh.',
                    "That's just Joblin.",
                    "She loves being close by, even when she's pretending to be asleep.",
                    "I have a feeling she's always keeping one eye on what's happening around here.",
                    'Something tells me life with Joblin is going to provide plenty of stories for future editions of Shadows Monthly.',
                    'Until next month...',
                    "I'm sure she'll have another adventure to tell us about.",
                ]),
            ],
            [
                'title' => "A Moment I'll Never Forget",
                'icon' => '❄️',
                'placement' => MonthlyEditionSection::PLACEMENT_BEFORE,
                'content' => $this->html([
                    'One of my favourite family memories takes us back to Kosciuszko National Park.',
                    'It was the very first time I had ever seen snow.',
                    "Like many Australians, I'd seen photographs of snow all my life, but nothing could have prepared me for seeing it with my own eyes.",
                    'As we drove into Jindabyne, the lake came into view and beyond it were the snow-covered mountains.',
                    'The sun was shining across the lake and onto the snow-covered mountains, making the snow sparkle like thousands of tiny diamonds.',
                    'All I could say was,',
                    '"Wow."',
                    'Before I knew it, tears were rolling down my face.',
                    'Not because I was sad...',
                    'But because it was one of the most beautiful things I had ever seen.',
                    "I don't think I'll ever forget that moment.",
                    'Of course, Shadow was with us.',
                    'She stayed close by my side, taking in all the new sights and smells around her.',
                    "I don't know who was more excited...",
                    'Me...',
                    'Shadow...',
                    'Or John, quietly standing back and watching the two of us take it all in.',
                    "One of the things that has stayed with me all these years wasn't actually the snow itself.",
                    'It was the early morning frost.',
                    'As the first rays of sunlight touched the ground, the whole landscape seemed to shimmer in the morning light.',
                    'It was breathtaking.',
                    "Looking back now, I've realised that the memories we treasure most aren't always about where we go.",
                    "They're about who we share them with.",
                    "Every time I look at this photograph, I'm taken back to that very first trip to the snow.",
                    'To the excitement.',
                    'To the wonder.',
                    'To standing there with John and Shadow beside me.',
                    "It's a moment I'll treasure for the rest of my life.",
                ]),
            ],
            [
                'title' => "We'd Love to Share Your Story",
                'icon' => '🌿',
                'placement' => MonthlyEditionSection::PLACEMENT_BEFORE,
                'content' => $this->html([
                    'One of the things we hope Shadows Monthly becomes is a place where Australians can share the memories that mean the most to them.',
                    'Do you have a favourite photograph and the story behind it?',
                    "Perhaps it's a family holiday, a camping trip, a beloved pet, a special celebration or simply a quiet moment that still makes you smile every time you see it.",
                    "It doesn't need to be taken with an expensive camera.",
                    "It doesn't need to be perfect.",
                    'It simply needs to tell a story.',
                    "If you'd like to share your photograph and your story, we'd love to hear from you. You might even find your memory featured in a future edition of Shadows Monthly.",
                    'Because every family has a story worth sharing.',
                ]),
            ],
            [
                'title' => 'Until Next Month...',
                'icon' => '☕',
                'placement' => MonthlyEditionSection::PLACEMENT_AFTER,
                'content' => $this->html([
                    'Well...',
                    "Our cuppas have long since gone cold, and it feels like it's time for me to let you get back to your day.",
                    'Thank you for spending a little time with us.',
                    'I hope something in this very first edition of Shadows Monthly has made you smile, reminded you of a special memory or perhaps even inspired you to make a few new ones of your own.',
                    "One of the things I've realised while putting this together is that life isn't really made up of the big moments.",
                    "It's the little ones we remember most.",
                    'A quiet morning with a cup of coffee.',
                    "A country road you've never travelled before.",
                    'A family gathering around the dinner table.',
                    "A child's laughter.",
                    'A loyal dog by your side.',
                    'The first time you see snow.',
                    'Or simply watching the sun rise over another beautiful part of Australia.',
                    'These are the moments that quietly become our memories.',
                    'As July unfolds, I hope you find a little time to slow down, look around and enjoy whatever this wonderful country has waiting for you.',
                    'Take a few photographs.',
                    'Write down a story.',
                    'Give someone you love a hug.',
                    "And if you happen to create a memory you'd like to share, we'd love to hear from you.",
                    'Perhaps your story will become part of a future edition of Shadows Monthly.',
                    'Until next month...',
                    'Take care of yourself.',
                    'Take care of those you love.',
                    'And above all...',
                    'Keep making memories.',
                    'From our family to yours,',
                    'Warm regards,',
                    'The Shadows Family',
                ]),
            ],
        ];
    }

    private function html(array $paragraphs): string
    {
        return collect($paragraphs)
            ->map(fn ($paragraph) => '<p>' . e($paragraph) . '</p>')
            ->implode('');
    }
}
